

package scrumproj;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfException;

public class BokadeMoten extends Page {

    public BokadeMoten (Application app) {
        super(app);
        initComponents();
    }

    @Override
    public void updateInfo() { 
          
        try {
            DefaultTableModel table = new DefaultTableModel(new Object[]{"BESKRIVNING", "DATUM", "TID"}, 0);

            ArrayList<HashMap<String, String>> allaRader;
            int inloggadId = app.getCurrentUser();
             allaRader = app.getDataBaseConnection().fetchRows("SELECT BESKRIVNING, DATUM, TID FROM MOTEN JOIN BOKADE_MOTEN ON MOTEN.MOTES_ID = BOKADE_MOTEN.MOTES_ID and BOKADE_MOTEN.ANVANDAR_ID = '"+inloggadId+"'");

            for (HashMap<String, String> rad : allaRader) {
                String beskrivning = rad.get("BESKRIVNING");
                String datum = rad.get("DATUM");
                String tid = rad.get("TID");
                

                //Sätter in anvandare + inlagg + datum  i tabellen mha addRow()
                table.addRow(new Object[]{beskrivning, datum, tid});
                
            }

            //Säger att tblInlagg ska använda sig av den modellen vi skapade ovan
            tblMoten.setModel(table);

            //Sätter defaultEditor till Object.class, null för att data i tabellen inte ska kunna redigeras, men kunna selekteras.
            tblMoten.setDefaultEditor(Object.class, null);

            //Stänger av möjligheten att ändra kolumnordningen.
            tblMoten.getTableHeader().setReorderingAllowed(false);

            //Sätter bredden på kolumnen som innehåller ID till 0px.
            //Vi vill inte att ID ska visas i listan men vill eventueltl kunna använda IDt 
            //tblMoten.getColumnModel().getColumn(3).setMinWidth(0);
            //tblMoten.getColumnModel().getColumn(3).setMaxWidth(0);
            //tblMoten.getColumnModel().getColumn(3).setWidth(0);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Du har för tillfället inga bokade möten!");
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMoten = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        tblMoten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMoten);

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       app.selectPage(13);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMoten;
    // End of variables declaration//GEN-END:variables
}
