package scrumproj;

import javax.swing.JOptionPane;
import oru.inf.InfException;
import java.time.LocalDateTime;   

/**
 *
 * @author Tor
 */
public class FormellBlogg extends Page {

   
    public FormellBlogg (Application app) {
        super(app);
        
        initComponents();
    }

    @Override
    public void updateInfo() { 
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPubliceraInlagg = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        InlaggsRutan = new javax.swing.JTextArea();

        btnPubliceraInlagg.setText("Publicera inlägg");
        btnPubliceraInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraInlaggActionPerformed(evt);
            }
        });

        jButton2.setText("Gå tillbaka");

        jButton3.setText("Profil");

        InlaggsRutan.setColumns(20);
        InlaggsRutan.setRows(5);
        jScrollPane4.setViewportView(InlaggsRutan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPubliceraInlagg)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPubliceraInlagg)
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPubliceraInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraInlaggActionPerformed
      
        try {
            if (!Validering.taHarVarde(InlaggsRutan)) {

            } else {
                String Inlagget = InlaggsRutan.getText();
                LocalDateTime tiden = LocalDateTime.now();
                int anvandare = app.getCurrentUser();
                var anvandaren = app.getDataBaseConnection().fetchSingle("SELECT FORNAMN FROM ANVANDARE WHERE ANVANDAR_ID= ''" + anvandare + "'");

                String id = app.getDataBaseConnection().getAutoIncrement("FORMELBLOGG", "INLAGG_ID");
                if (id == null) {
                    id = "1";
                }

                String inlagg = app.getDataBaseConnection().fetchSingle("INSERT INTO FORMELBLOGG (ANVANDARE, INLAGG_ID, TIDSTAMPEL, INLAGG) VALUES (''" + anvandaren + "','" + id + "','" + tiden + "','" + Inlagget + "')");
                JOptionPane.showMessageDialog(null, "Du har nu publicerat ditt inlägg!");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något blev fel, försök igen!");
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPubliceraInlaggActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InlaggsRutan;
    private javax.swing.JButton btnPubliceraInlagg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
