package scrumproj;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfException;

public class RedigeraInlagg extends Page {

    public RedigeraInlagg(Application app) {
        super(app);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        cbocValjAnvandare = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtInlagg = new javax.swing.JTextField();
        btnBekrafta = new javax.swing.JButton();
        btnHamta = new javax.swing.JButton();
        lblTomtFalt = new javax.swing.JLabel();
        lblTaxten = new javax.swing.JLabel();
        lblFelmeddelande = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        cbocValjAnvandare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Gå tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBekrafta.setText("Bekräfta ");
        btnBekrafta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBekraftaActionPerformed(evt);
            }
        });

        btnHamta.setText("Hämta");
        btnHamta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblTomtFalt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnHamta)
                                .addComponent(cbocValjAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(49, 49, 49)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaxten, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBekrafta)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(cbocValjAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHamta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(lblTaxten)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFelmeddelande)
                    .addComponent(btnBekrafta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTomtFalt)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        app.selectPage(17);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBekraftaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBekraftaActionPerformed
       
        if (cbocValjAnvandare.getItemCount() == 0) {
            lblFelmeddelande.setText("Välj ett inlägg!");
        } else {
        try {
            String valtInlagg = cbocValjAnvandare.getSelectedItem().toString();
            String inlaggId = app.getDataBaseConnection().fetchSingle("SELECT INLAGG_ID FROM FORMELBLOGG WHERE INLAGG ='" + valtInlagg + "'");
            String nyttInlagg = txtInlagg.getText();

            if (!Validering.tfIsTomt(txtInlagg)) {
                app.getDataBaseConnection().update("UPDATE FORMELBLOGG SET INLAGG = '" + nyttInlagg + "' WHERE INLAGG_ID = " + inlaggId + "");
                lblFelmeddelande.setText("Uppdatering av inlägget lyckades!");
             if (Validering.tfIsTomt(txtInlagg)) {
                    lblFelmeddelande.setText("Vänligen lämna inte rutan tom.");

                }
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något blev fel, försök igen!");
            System.err.println(e);
        }
        }
    }//GEN-LAST:event_btnBekraftaActionPerformed

    private void btnHamtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamtaActionPerformed
    
        if (cbocValjAnvandare.getItemCount() == 0) {
            lblFelmeddelande.setText("Välj ett inlägg!");
        } else {
            try {

                String valtInlagg = cbocValjAnvandare.getSelectedItem().toString();
                String inlaggId = app.getDataBaseConnection().fetchSingle("SELECT INLAGG_ID FROM FORMELBLOGG WHERE INLAGG = '" + valtInlagg + "'");
                txtInlagg.setText(app.getDataBaseConnection().fetchSingle("SELECT INLAGG FROM FORMELBLOGG WHERE INLAGG_ID = '" + inlaggId + "'"));

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något blev fel, försök igen!");
                System.err.println(e);
            }


        }
    }//GEN-LAST:event_btnHamtaActionPerformed

    @Override
    public void updateInfo() {

        ArrayList<String> allaAnvandare;
        cbocValjAnvandare.removeAllItems();

        try {

            String fraga = "SELECT INLAGG_ID FROM FORMELBLOGG";

            allaAnvandare = app.getDataBaseConnection().fetchColumn(fraga); // hämta alla inlägg
            
            //En for loop som lägger in datan i en combobox för vare instans som uppstår.
            for (String id : allaAnvandare) {

                String inlagg = app.getDataBaseConnection().fetchSingle("SELECT INLAGG FROM FORMELBLOGG WHERE INLAGG_ID = '" + id + "'");
                cbocValjAnvandare.addItem(inlagg);
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (Exception ettUndantag) {
            lblFelmeddelande.setText("Det finns inga inlägg!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBekrafta;
    private javax.swing.JButton btnHamta;
    private javax.swing.JComboBox<String> cbocValjAnvandare;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblTaxten;
    private javax.swing.JLabel lblTomtFalt;
    private javax.swing.JTextField txtInlagg;
    // End of variables declaration//GEN-END:variables
}
