/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumproj;

import javax.swing.JOptionPane;
import oru.inf.InfException;

public class RegistreraAnvandare extends Page {

    public RegistreraAnvandare (Application app) {
        super(app);
        initComponents();
    }

    @Override
    public void updateInfo() { }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EPOST = new javax.swing.JTextField();
        LOSENORD = new javax.swing.JPasswordField();
        FORNAMN = new javax.swing.JTextField();
        EFTERNAMN = new javax.swing.JTextField();
        TELEFONNUMMER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ADRESS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        administratorBox = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(640, 640));

        jLabel1.setText("Epost");

        jLabel2.setText("Lösenord");

        jLabel3.setText("Förnamn");

        jLabel4.setText("Efternamn");

        jLabel5.setText("Telefonnummer");

        EPOST.setToolTipText("");
        EPOST.setName(""); // NOI18N

        LOSENORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOSENORDActionPerformed(evt);
            }
        });

        FORNAMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORNAMNActionPerformed(evt);
            }
        });

        EFTERNAMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EFTERNAMNActionPerformed(evt);
            }
        });

        TELEFONNUMMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELEFONNUMMERActionPerformed(evt);
            }
        });

        jLabel6.setText("Adress");

        ADRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADRESSActionPerformed(evt);
            }
        });

        jLabel7.setText("Registrera en ny användare");

        jButton1.setText("Slutför registrering");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tillbaka till menyn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        administratorBox.setText("Admin?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(administratorBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FORNAMN)
                                        .addComponent(LOSENORD, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(EPOST)
                                        .addComponent(EFTERNAMN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TELEFONNUMMER)
                                        .addComponent(ADRESS)))))
                        .addContainerGap(440, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EPOST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LOSENORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FORNAMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(EFTERNAMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TELEFONNUMMER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(administratorBox)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LOSENORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOSENORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOSENORDActionPerformed

    private void FORNAMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORNAMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FORNAMNActionPerformed

    private void EFTERNAMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EFTERNAMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EFTERNAMNActionPerformed

    private void TELEFONNUMMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELEFONNUMMERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TELEFONNUMMERActionPerformed

    private void ADRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADRESSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
  if (administratorBox.isSelected()) {
    String epost = EPOST.getText();
    String losenord = new String(LOSENORD.getPassword());
    String fornamn = FORNAMN.getText();
    String efternamn = EFTERNAMN.getText();
    String telefon = TELEFONNUMMER.getText();
    String adress = ADRESS.getText();
    String id = app.getDataBaseConnection().getAutoIncrement("ANVANDARE", "ANVANDAR_ID");
    if (id == null) {
        id = "1";
    }
    String svar = app.getDataBaseConnection().fetchSingle("INSERT INTO ANVANDARE (ANVANDAR_ID, FORNAMN, EFTERNAMN, EPOST, LOSENORD, ADRESS, ADMINSTATUS, TELEFONNUMMER) VALUES ('"+id+"', '"+fornamn+"', '"+efternamn+"', '"+epost+"', '"+losenord+"', '"+adress+"', '"+"J"+"','"+telefon+"')");
        JOptionPane.showMessageDialog(null, "Du har nu registrerat en ny användare!");
  }
  else {
     String epost = EPOST.getText();
    String losenord = new String(LOSENORD.getPassword());
    String fornamn = FORNAMN.getText();
    String efternamn = EFTERNAMN.getText();
    String telefon = TELEFONNUMMER.getText();
    String adress = ADRESS.getText();
    String id = app.getDataBaseConnection().getAutoIncrement("ANVANDARE", "ANVANDAR_ID");
    if (id == null) {
        id = "1";
    }
    String svar = app.getDataBaseConnection().fetchSingle("INSERT INTO ANVANDARE (ANVANDAR_ID, FORNAMN, EFTERNAMN, EPOST, LOSENORD, ADRESS, ADMINSTATUS, TELEFONNUMMER) VALUES ('"+id+"', '"+fornamn+"', '"+efternamn+"', '"+epost+"', '"+losenord+"', '"+adress+"', '"+"N"+"','"+telefon+"')");
        JOptionPane.showMessageDialog(null, "Du har nu registrerat en ny användare!");
  
  }
  
    }
    
    catch(InfException e)
    {
     JOptionPane.showMessageDialog(null, "Något blev fel, försök igen!");
     System.err.println(e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
app.selectPage(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADRESS;
    private javax.swing.JTextField EFTERNAMN;
    private javax.swing.JTextField EPOST;
    private javax.swing.JTextField FORNAMN;
    private javax.swing.JPasswordField LOSENORD;
    private javax.swing.JTextField TELEFONNUMMER;
    private javax.swing.JCheckBox administratorBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
